# Generated by Django 4.2.8 on 2023-12-06 01:01

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='page_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock())], default='', use_json_field=True),
            preserve_default=False,
        ),
    ]
