# Generated by Django 4.2.8 on 2023-12-06 02:16

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('section', wagtail.blocks.StructBlock([('section_title', wagtail.blocks.CharBlock()), ('section_content', wagtail.blocks.StreamBlock([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock())]))]))], use_json_field=True),
        ),
    ]
