# Generated by Django 4.2.8 on 2023-12-07 14:58

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_homepage_page_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sidebar_color',
            field=wagtail_color_panel.fields.ColorField(default='#000000', max_length=7),
        ),
    ]
