# Generated by Django 4.2.8 on 2024-06-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0011_remove_homepage_hero_image_genericsitesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomePage',
            new_name='ContentPage',
        ),
    ]
