# Generated by Django 4.2.8 on 2024-06-19 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('home', '0012_rename_homepage_contentpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentPage',
            new_name='HomePage',
        ),
    ]
