# Generated by Django 4.2.8 on 2024-06-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_rename_contentpage_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='button_color',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='sidebar_color',
        ),
    ]
