# Generated by Django 4.2.8 on 2024-06-19 00:53

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_homepage_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='page_body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title')), ('paragraph', wagtail.blocks.RichTextBlock()), ('numbered_list', wagtail.blocks.StreamBlock([('item', wagtail.blocks.RichTextBlock())])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video_embed', wagtail.blocks.TextBlock())], use_json_field=True),
        ),
    ]
